### ISSUE TITLE
nested map can't be declared before parent

### ISSUE THREAD

**Issue by guai** [TheElectronWill/Night-Config#10]
This example from [toml](https://github.com/toml-lang/toml) does not work:

> As long as a super-table hasn't been directly defined and hasn't defined a specific key, you may still write to it.
```toml
[a.b]
c = 1
[a]
d = 2
```

**Comment by TheElectronWill** [comment]
Well spotted!

It seems that the TomlParser actually parses both table parts correctly, but it replaces the first "a" it creates by the last one, losing the subtable "b".

I'll fix this and add some tests to prevent a regression.

Thanks!
