### ISSUE TITLE
Cannot import com.electronwill.nightconfig.core.SimpleCommentedConfig

### ISSUE THREAD

**Issue by brytemorio** [TheElectronWill/night-config#100]
I tried parsing a toml configuration file that contained _inline tables_

Example snippets:
```toml
#config.toml
[Blockchain.Waves]
field_name = {key1="value2", key2="value2"} 
```

```java
//read and parse config.toml
Charset CHARSET = StandardCharsets.ISO_8859_1;
Path tomlConfigFile = Paths.get("path/to/config.toml/file");
CommentedConfig CONFIG = new TomlParser().parse(tomlConfigFile, FileNotFoundAction.THROW_ERROR, CHARSET);

//get the values 
HashMap<String, String> value = CONFIG.get("Blockchain.Waves.field_name") //runtime error
```

The resulting error:
```block
Exception in thread "main" java.lang.ClassCastException:
class com.electronwill.nightconfig.core.SimpleCommentedConfig cannot be cast to class java.util.HashMap
```

But from futher inspection of the com.electronwill.nightconfig.core.SimpleCommentedConfig because I could not import it.
IntelliJ flagged the class with the hints below:
```java
'com.electronwill.nightconfig.core.SimpleCommentedConfig' is not public in 'com.electronwill.nightconfig.core'. Cannot be accessed from outside package

package-private final class SimpleCommentedConfig extends com.electronwill.nightconfig.core.AbstractCommentedConfig
```

 I doubled checked with other editors and IDE, same issue

**Comment by TheElectronWill** [comment]
Sub-configurations are stored as `Config` objects, not HashMap. This is useful for several reasons.

As stated in [the wiki](https://github.com/TheElectronWill/night-config/wiki/Configurations) you should use the `Config` interface:
```java
Config value = CONFIG.get("Blockchain.Waves.field_name") //runtime error
```
SimpleCommentedConfig is for internal use only (internal to the library), users should use the abstract types like `UnmodifiableConfig`, `Config`, `CommentedConfig`, etc.
