### ISSUE TITLE
TomlFormat claims to support null values

### ISSUE THREAD

**Issue by TechnicianLP** [TheElectronWill/night-config#101]
Calling `TomlFormat.instance().supportsType(null)` returns `true`, which according to the javadoc in `ConfigFormat` indicates that null values are supported. 
This allows null values to be written into a `CheckedConfig` instance and can lead to an Exception being thrown when the Config is written using the `ValueWriter`

**Comment by TheElectronWill** [comment]
Could you provide the stack trace and the code/config that produces it please?

**Comment by TechnicianLP** [comment]
The issues is with the `TomlFormat#supportsType` method returning `true` on `null` whereas it should be returning `false` since TOML doesnt support null values. 
This in turn allows null values to be written into a CheckedConfig that should not allow them, which can lead to subsequent issues.

Code Example and Output attached
[TomlNull.java.txt](https://github.com/TheElectronWill/night-config/files/7824617/TomlNull.java.txt)
[TomlNull.output.txt](https://github.com/TheElectronWill/night-config/files/7824623/TomlNull.output.txt)

While putting together the Example ive noticed CheckedFileConfig doesnt not check "The values that are in the config when this method is called [...]". Since FileConfig Instances are wrapped i didnt manage to create an Example that calls checked() on a bare FileConfig Instance. CheckedConfig does perform the check as described in the javadoc.

**Comment by TheElectronWill** [comment]
You're right, `supportsTypes(null)` should indeed be false. I'll take a look at the PR soon.
