### ISSUE TITLE
com.electronwill.nightconfig.core.file.NoFormatFoundException: No suitable format for configg.toml

### ISSUE THREAD

**Issue by Skjolberg** [TheElectronWill/night-config#109]
I am having the same mistake as this man: https://github.com/TheElectronWill/Night-Config/issues/33

i use gradle kts:
repositories {
mavenCentral()
}

dependencies {
implementation("com.electronwill.night-config:core:3.6.5")
implementation("com.electronwill.night-config:toml:3.6.5")
}

If I do "compileOnly" it doesn't find the class, so I'm using implementation, I don't know why I'm getting this error.

FileConfig config = FileConfig.of(plugin.getDataFolder()+"/configg.toml");

**Comment by TheElectronWill** [comment]
`implementation` looks like the correct thing to use here.
Are you sure that the plugin's JAR that you produce does contain night-config? That might explain why it doesn't load the toml format.

You can also try specifying the format manually, by using `TomlFormat.instance()` (see [here](https://github.com/TheElectronWill/night-config/wiki/Config-formats))
