### ISSUE TITLE
triple quotes issue

### ISSUE THREAD

**Issue by guai** [TheElectronWill/Night-Config#11]
```toml
str1 = """
Roses are red
Violets are blue"""
```
this toml example does not parse

**Comment by TheElectronWill** [comment]
This produces an error `ParsingException: Invalid character '"' after table entry "str1"`
Looks like it's due to an incorrect parsing of multiline strings.

Thanks for reporting!

**Comment by TheElectronWill** [comment]
As usual I've added more tests. (I should have tested multiline string sooner, my bad)

**Comment by guai** [comment]
Thanks for another one superquick-fix :)

**Comment by TheElectronWill** [comment]
I've ported the fixes to stable branch.
