### ISSUE TITLE
 Access problem

### ISSUE THREAD

**Issue by mani1232** [TheElectronWill/night-config#116]
![image](https://user-images.githubusercontent.com/70480001/190012762-eb132e61-24c4-448a-acf3-65f96a38d5c0.png)

**Comment by TheElectronWill** [comment]
Hi!
The builder's constructor is for NightConfig's internal only. To create one, use
```java
CommentedFileConfig.builder()
// or
FileConfig.builder()
```

As shown in the [README](README.md)

**Comment by mani1232** [comment]
> Hi! The builder's constructor is for NightConfig's internal only. To create one, use
> 
> ```java
> CommentedFileConfig.builder("path/to/file")
> // or
> FileConfig.builder("path/to/file")
> ```
> 
> As shown in the [README](README.md)

Ok, but how to make it so that if there is no file, then it is created from resources

**Comment by mani1232** [comment]
![image](https://user-images.githubusercontent.com/70480001/190087259-c3d6a815-0ac1-478d-892d-1f07de95f72c.png)
Example

**Comment by mani1232** [comment]
> In your screenshot the files seem to be outside of your jar, so they're not jar resources 🤔 When you have jar resources, give their `Path` to the builder function:
> 
> ```java
> URL resource = YourClass.class.getResource("resource-config.toml"); // get the resource URL
> // Note: replace YourClass by some class of your project :)
> 
> Path path = Paths.get(resource.toURI()); // transform the URL to a Path
> FileConfigBuilder builder = FileConfig.builder(path); // create the builder
> ```
> 
> See https://stackoverflow.com/questions/17351043/how-to-get-absolute-path-to-file-in-resources-folder-of-your-project


these files are in the resources, the example indicates how they should be after launch, is there a method for creating a file if it is not
https://github.com/mani1232/DoubleTickets/tree/master/src/main/resources

**Comment by TheElectronWill** [comment]
In that case the `path` that you must give to FileConfig.builder is the one of the file that you want to create, and you use `builder.defaultResource` to indicate where your resource is.

See an example in [the wiki](https://github.com/TheElectronWill/night-config/wiki/FileConfigBuilder).

**Comment by mani1232** [comment]
> В этом случае `path`вы должны предоставить FileConfig.builder файл, который вы хотите создать, и который вы используете `builder.defaultResource`, чтобы указать, где находится ваш ресурс. Если файл не существует, он будет создан с содержимым ресурса.
> 
> См. пример в [вики](https://github.com/TheElectronWill/night-config/wiki/FileConfigBuilder) . Для вас это будет выглядеть так:
> 
> ```java
> FileConfigBuilder builder = FileConfig.builder("file-to-create.toml");
> FileConfig = builder.defaultResource("/path/to/resource-file.toml").sync().build();
> ```
https://github.com/mani1232/DoubleTickets/blob/master/src/main/java/ua/mani123/DTBot.java#L43
But files are not created

**Comment by TheElectronWill** [comment]
The files are only created when you `load()` the config.

**Comment by mani1232** [comment]
I meant is there something similar in your library?
https://github.com/mani1232/DoubleTickets/blob/master/src/main/java/ua/mani123/DTBot.java#L136

**Comment by TheElectronWill** [comment]
Yes there is. That's what a builder with `defaultResource` does on `load()`.
It sets a `FileNotFoundAction` of kind `copyData` (defined [here](https://github.com/TheElectronWill/night-config/blob/8d0cd781813535a528f245b63ec4bf3eccf07396/core/src/main/java/com/electronwill/nightconfig/core/file/FileNotFoundAction.java#L77)). This `FileNotFoundAction` is passed to the `parser` in `load()` [here](https://github.com/TheElectronWill/night-config/blob/8d0cd781813535a528f245b63ec4bf3eccf07396/core/src/main/java/com/electronwill/nightconfig/core/file/WriteSyncFileConfig.java#L67). The `parser` runs this `FileNotFoundAction` [when the file doesn't exist](https://github.com/TheElectronWill/night-config/blob/8d0cd781813535a528f245b63ec4bf3eccf07396/core/src/main/java/com/electronwill/nightconfig/core/io/ConfigParser.java#L181).
