### ISSUE TITLE
Add only if not found

### ISSUE THREAD

**Issue by mani1232** [TheElectronWill/night-config#117]
```toml 
[965722681238503524]
	guild-name = "Тестовый сервер"

	[965722681238503524.792689746156978207]
		username = "WorldMandia тест"

	[965722681238503524.486559882825302027]
		username = "mani123"
		personal-counter = 1
```
I have such a situation, how can I allow me to manually add new sections to this config so that the section is not deleted when turned off or reload
https://github.com/mani1232/CustomBot/blob/master/src/main/java/ua/mani123/listeners/onReadyListener.java#L29

**Comment by TheElectronWill** [comment]
Hmm, the title says "add only if not found" but then you ask something different 😅

> add new sections to this config so that the section is not deleted when turned off or reload

Have you saved the config with `config.save()`? Or used `autosave()` mode in the builder?

Please take a look at the [example](https://github.com/TheElectronWill/night-config/blob/master/examples/src/main/java/FileConfigExample.java).

**Comment by mani1232** [comment]
https://github.com/mani1232/CustomBot/blob/master/src/main/java/ua/mani123/listeners/onReadyListener.java#L28#L41
I fixed it by adding 'if'
