### ISSUE TITLE
ConfigSpec defineInRange doesn't play nicely with Long values

### ISSUE THREAD

**Issue by Nightenom** [TheElectronWill/night-config#119]
Hi, not a breaking bug, but using [`configSpec.defineInRange(path, defaultValue, min, max);`](https://github.com/TheElectronWill/night-config/blob/master/core/src/main/java/com/electronwill/nightconfig/core/ConfigSpec.java#L309) causes `java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer` during configSpec.correct(...) which yields ConfigSpec.CorrectAction.REPLACE to correction listener

```
java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')
        at java.base/java.lang.Integer.compareTo(Integer.java:71)
        at com.electronwill.nightconfig.core@3.6.6/com.electronwill.nightconfig.core.ConfigSpec.lambda$defineInRange$2(ConfigSpec.java:309)
        at com.electronwill.nightconfig.core@3.6.6/com.electronwill.nightconfig.core.ConfigSpec.correct(ConfigSpec.java:641)
        at com.electronwill.nightconfig.core@3.6.6/com.electronwill.nightconfig.core.ConfigSpec.correct(ConfigSpec.java:636)
        at com.electronwill.nightconfig.core@3.6.6/com.electronwill.nightconfig.core.ConfigSpec.correct(ConfigSpec.java:595)
```

**Comment by TheElectronWill** [comment]
Hello

Can you show me how you call `defineInRange` exactly?

**Comment by Nightenom** [comment]
Types from IDE hint: `<Long> void com.electronwill.nightconfig.core.ConfigSpec.defineInRange(List<String> path, Long defaultValue, Long min, Long max)`
Real types passed in are long primitives and LinkedList<String> (cuz I build path using a FIFO stack)
Integer is passed here from Toml parser

Also you probably have typo in method desc: `Defines an entry. A config value is considered correct if and only if it is less than or equal to {@code min} and bigger than or equal to {@code max}.` Shouldn't it be "bigger than min" and "less than max"?

**Comment by TheElectronWill** [comment]
If your config value is an int you should call `defineInRange` with the same type, i.e. int. I agree that it could be improved, I mark this issue as such :)

> Shouldn't it be "bigger than min" and "less than max"?

Yes, absolutely! good catch.

**Comment by Nightenom** [comment]
Well, despite you're right, after deaper investigation the problem lies in [toml value parser](https://github.com/TheElectronWill/night-config/blob/master/toml/src/main/java/com/electronwill/nightconfig/toml/ValueParser.java#L129-L132) - this type assumption is kinda problematic as parser has no idea about configSpec.
But the problem described above might be solveable just by swapping tested object and boundaries to `return min.compareTo(c) <= 0 && max.compareTo(c) >= 0;` which means that compareTo is invoked on boundaries rather than parser result

**Comment by TheElectronWill** [comment]
the type assumption allows to return int whenever it's possible, it's a "workaround" for the lack of information that the parser has.
It would be better to make it an option of the parser, but really, you shouldn't use Long in the spec if your values are in the int range.

**Comment by TheElectronWill** [comment]
long->int and double->float conversions are potentially lossy, it would be dangerous to apply them in a non-obvious way.

But I could make it configurable, ofc. ^^

**Comment by TheElectronWill** [comment]
The situation is now improved thanks to fc3df2aff234a287e5c58fc69c58f3de8f5d6cc8 and 5e7789b1d0f21ab878b8485bd416d37e03d154e2
