### ISSUE TITLE
Suggestion: Less strict ConfigSpec (not deleting unspecified values)

### ISSUE THREAD

**Issue by brainbytes42** [TheElectronWill/night-config#129]
Hi,

I'm currently evaluating the best way to model a set of default values, but there are no defaults for _all_ entries.

My first approach was to load a default file if the user hasn't provided a file and then show a warning regarding the values where no default is available. 

Second approach: Load the file and add all from the default to additionally have fallback values, if the user hasn't specified each and every value - e.g. only specified the _changed_ values and don't bother with defaults... (Is there a better way to realize this? This way, if the user-config leaves a value unspecified, I can change the default by providing a new jar...)

Third approach: Use ConfigSpec. I like the concept, and if I don't write back the changed config, I can model the second approach in which I only specify relevant changes but not repeat existing defaults. But is there a way to make the correctness-check less strict? I'd prefer to correct the specified values, but NOT delete unspecified values. (i.e. ignore the second condition as specidied in ConfigSpec's docs.) This is due to the fact, that I have a list of sub-configurations, for which the modeling seems quite difficult...

Maybe one could add a flag to the constructor like ConfigSpec(ignoreUnspecified)...?

**Comment by TheElectronWill** [comment]
If you have a list of subconfigurations, you should be able to simply `define` the list itself (not its elements).
I'm thinking about something like:
```java
spec.define("path.to.list_of_configs", ArrayList::new, obj -> checkMyList(obj))
```
