### ISSUE TITLE
[question] How to use configspec to correct (Commented)FileConfig?

### ISSUE THREAD

**Issue by PORTB** [TheElectronWill/night-config#135]
Hello
I'm trying to use ConfigSpec to correct any invalid values in a FileConfig for a project I'm making. Here is a simplified version of what I'm doing:

```java
var spec = new ConfigSpec();

spec.define("stuff", false);

var config = CommentedFileConfig.of("somefile.toml");

config.load(); //com.electronwill.nightconfig.core.io.ParsingException: Invalid value: TRUE

spec.correct(config);

System.out.println((boolean)config.get("stuff")); //should be false
```
somefile.toml
```toml
stuff=TRUE #invalid
```
However, it causes an exception when I try to load the file, so the configspec can't correct the file.

How do I achieve this?

**Comment by TheElectronWill** [comment]
Hello!
    
The error isn't in your use of ConfigSpec, it's your toml file that is incorrect, which causes the ParsingException.

Instead of `TRUE` it should be `true` in lowercase.
