### ISSUE TITLE
ConversionTable for ObjectConverter - based on Target Type

### ISSUE THREAD

**Issue by brainbytes42** [TheElectronWill/night-config#156]
Hi,

I am trying to read my (TOML-)ConfigFile into an POJO using the ObjectConverter.

I have several Durations, for example, and other custom objects. Using the `@Conversion`-Annotation, I'm able to parse my file successfully.

My Question/Suggestion ist the following:
As the ObjectConverter relies on Reflection to set the Fields, it should be possible to read the field's types - wouldn't it be nice, to provide a ConversionTable selecting the converter based on the POJO's field? 
Currently, as far as I understood, the `ConversionTable` is applied to _all_ Strings (or what TOML-type is specified), so it wouldn't be possible to habe a path (string) and a Duration side by side (without annotating each non-string field separately).
If the COnverter could select for all Duration- (or Whatever-)fields the Duration- (or Whatever-)Converter from the conversion table, one would have to provide the converter only once and the config POJO would be more clean.

Any thoughts on this? :-)

**Comment by TheElectronWill** [comment]
I can think of a nice way to do that: give a special conversion table to the `ObjectConverter`, taking into account the type (toml value type) and destination type (Java field type). WDYT?

**Comment by brainbytes42** [comment]
That would be cool 🙂
