### ISSUE TITLE
Supporting records

### ISSUE THREAD

**Issue by brainbytes42** [TheElectronWill/night-config#159]
Hi,
are there any plans to support java records as ObjectConverter-targets? As they don't have an empty constructor, currently this seems not possible?

**Comment by TheElectronWill** [comment]
Hello!

Records aren't supported out-of-the box for now, but you could try to add a custom conversion.
It should be possible to modify the ObjectConverter to support records, I have to think about a way of handling newer versions of Javas at the same time as Java 8.

Some links for my future self who will implement that feature:
- https://stackoverflow.com/questions/67126109/is-there-a-way-to-recognise-a-java-16-records-canonical-constructor-via-reflect

**Comment by TheElectronWill** [comment]
Okay, I'm onto something with multi-release-jars. Serialization and deserialization of records is working with the new `serde` package of #163 :tada:

**Comment by brainbytes42** [comment]
sounds promising - I'm looking forward to it :-)

**Comment by brainbytes42** [comment]
You seemed to be very active on this project recently 👍👍 - any plans for a new release? 😊

**Comment by TheElectronWill** [comment]
Yes, I've already written the draft of the new release actually :)
I'll release it once #164 is done.
