### ISSUE TITLE
json files can have arbitrary data on the end of them

### ISSUE THREAD

**Issue by nextdayy** [TheElectronWill/night-config#167]
following a json file (parsed using `JsonFormat.fancyInstance().createParser()`), 
```json
{
	"chicken": true,
	"cgow": false,
	"color": {
		"saturation": 1.0,
		"brightness": 1.0,
		"alpha": 1.0,
		"hue": 0.9346405,
		"class": "org.polyfrost.polyui.color.PolyColor"
	},
	"cow5": false,
	"added": false,
	"i": 0,
	"cow2": false
} hdeajdiowaghuieanbdcjsaklfbuiawdaufhuaia
```
arbitrary data can be placed at the end of the file and it still accepts it (I do not think it is processed, however). not sure if this is a massive issue but is unusual behavior - most parsers would reject the above for it.

**Comment by TheElectronWill** [comment]
That should be rejected, indeed.
Thank you for reporting this bug!

**Comment by nextdayy** [comment]
thank you for the speedy fix!
