### ISSUE TITLE
Regression in dependencies since rewrite of gradle build using Kotlin DSL

### ISSUE THREAD

**Issue by murdos** [TheElectronWill/night-config#173]
In [our project](https://github.com/jhipster/jhipster-lite) we have a direct dependency to `com.electronwill.night-config:toml` and have not declared transitive dependency `com.electronwill.night-config:core`.

This was working fine with version 3.6.7, but this breaks with release 3.7.0, probably because the dependency was declared with the `implementation` scope, instead of the `compile` scope: https://github.com/TheElectronWill/night-config/commit/a28de26d47a5cb779894ffbe6e46d0011f06ce83#diff-7ad97c2e202fcb1d5aaf7d96f47fefd0ecf6d9f7f11d51d68584abfa9fb0f63aR11

You can compare generated pom.xml : 
- for version 3.6.7 : https://repo1.maven.org/maven2/com/electronwill/night-config/toml/3.6.7/toml-3.6.7.pom
```xml
<dependency>
<groupId>com.electronwill.night-config</groupId>
<artifactId>core</artifactId>
<version>3.6.7</version>
<scope>compile</scope>
</dependency>
```
- for version 3.7.0 : https://repo1.maven.org/maven2/com/electronwill/night-config/toml/3.7.0/toml-3.7.0.pom
```xml
<dependency>
<groupId>com.electronwill.night-config</groupId>
<artifactId>core</artifactId>
<version>3.7.0</version>
<scope>runtime</scope>
</dependency>
```

**Comment by TheElectronWill** [comment]
You are right, it should be `api` instead of `implementation` (`compile` has been deprecated for some time already). I'll release v3.7.1 to fix that.

Thank you for opening an issue!
