### ISSUE TITLE
Incorrect parse of TOML example

### ISSUE THREAD

**Issue by t-boom** [TheElectronWill/Night-Config#22]
When parsing a file ([like this one](https://github.com/toml-lang/toml/blob/master/tests/example.toml) for example) with CRLF endings, comments retain the CR at the end, but not the LF.

**Comment by t-boom** [comment]
This means that, among other things, the parsed config cannot be written back out. The `splitLines(String, List<String>)` function only checks if the current character is a CR. It then writes the current line and updates the position to be after the assumed LF. However, since the CR was the last character and there is no LF, the final statement fails (`pos0` is now greater than `str.length()`).

**Comment by TheElectronWill** [comment]
Thanks for reporting this!
Indeed, the parser should not retain the CR at the end of the line. I think I've got a fix, just need to test it... I'll push it in the next days.

**Comment by TheElectronWill** [comment]
This should have been fixed by the fix in TableParser in commit f54fb3de62dbda677876ac9d8bf83e9adb505f69 (master branch)
Tell me if you've still got problems.

**Comment by t-boom** [comment]
Awesome, thanks for the quick response. Any estimate on when to expect the 2.1.3 release?

**Comment by TheElectronWill** [comment]
I've nearly finished. It should be ready later today or tomorrow morning :-)
