### ISSUE TITLE
clearComments does't actually clear comments

### ISSUE THREAD

**Issue by t-boom** [TheElectronWill/Night-Config#25]
As stated, `AbstractCommentedConfig.clearComments()` doesn't actually clear the comments. It clears the comment map, but the entry set still contains its comments, and that is what is referenced when writing the file, so the comments remain.

**Comment by TheElectronWill** [comment]
Clearing the map should clear the entry set because both are linked. I'll do some tests 🤔

**Comment by TheElectronWill** [comment]
I see what the problem is: the comments may be stored in subconfigs, but only the root map is cleaned when clearComments() is called. The subconfigs' comments should be cleared recursively.
