### ISSUE TITLE
Commented File Config autosave doesn't automatically save

### ISSUE THREAD

**Issue by cpw** [TheElectronWill/Night-Config#41]
````
configData = CommentedFileConfig.builder(configFile).autosave().autoreload().build();
````
This code won't generate a config that is autosaving. It looks the resultant config object doesn't delegate to the right config to accomplish autosave - it's calling through to the normal config, not the autosaving one (there seems to be two?).

````
            configData.add("newsetting", "fish");
            configData.setComment("newsetting", "Super secret new setting");
````
Doesn't result in the config file being written with the new value or the new comment for said value.

**Comment by TheElectronWill** [comment]
Should be fixed by c1e286259c966a62b12afd29051ccf72face0219
Thanks for reporting
