### ISSUE TITLE
The writer doesn't flush it's contents

### ISSUE THREAD

**Issue by cpw** [TheElectronWill/Night-Config#42]
https://github.com/TheElectronWill/Night-Config/blob/e4f3d8fe958430cf22b81a78cf29f5057856d46e/core/src/main/java/com/electronwill/nightconfig/core/io/ConfigWriter.java#L42-L45

After debugging - it seems that for small config files, the buffered writer never actually flushes itself, resulting in no configuration being written to disk.

Confirming that running a flush via the debugger results in a config file being output.

**Comment by TheElectronWill** [comment]
I think that this writer should totally be auto-closed by a try-with-resources.
