### ISSUE TITLE
Incorrect type when using ObjectConverter on array of tables

### ISSUE THREAD

**Issue by p-v-d-Veeken** [TheElectronWill/Night-Config#47]
I believe I've found a bug in how the ObjectConverter handles an array of tables. To reproduce:

### 1. Create: /path/to/file.toml
```
[[b.cees]]
someString = "test1"
someInt = 123
[[b.cees]]
someString = "test2"
someInt = 456
```
### 2. Create MWE.java
```java
import com.electronwill.nightconfig.core.conversion.ObjectConverter;
import com.electronwill.nightconfig.core.file.FileConfig;

import java.util.List;

public class MWE {
    public static class A {
        B b;

        public A() { }
    }

    public static class B {
        List<C> cees;

        public B() { }
    }

    public static class C {
        String someString;
        int someInt;

        public C() { }
    }

    public static void main(String[] args) {
        FileConfig tomlFile = FileConfig.of("/path/to/file.toml").checked();

        tomlFile.load();

        A a = new ObjectConverter().toObject(tomlFile, A::new);

        System.out.println(a.b.cees.get(1).someString);
    }
}
```
### 3. Run MWE.java
Expected output: `test2`
Actual output: 
```
Exception in thread "main" java.lang.ClassCastException: com.electronwill.nightconfig.core.SimpleCommentedConfig cannot be cast to MWE$C
	at MWE.main(MWE.java:33)
```

**Comment by TheElectronWill** [comment]
Thanks for reporting!
Due to type erasure, ObjectConverter isn't aware that the list is a `List<C>`, it just sees a `List` and fills it with the parsed elements, i.e. config objects.
However, there seems to be [a way to get the `C` parameter in that case](https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/ParameterizedType.html#getActualTypeArguments--). I'll try to implement it.

**Comment by TheElectronWill** [comment]
I've implemented a quick-fix for your example (single-level List with a straightforward generic parameter) in f627c7875d9b811319f853a3d349d1458514d15c.
I'd like to improve it to support nested lists before releasing a new version of NightConfig.

**Comment by p-v-d-Veeken** [comment]
Thanks for the quick response and fix. Really awesome!

**Comment by p-v-d-Veeken** [comment]
Hi, could you provide an update on how this is going? If you need help with anything, I'd be happy to take a look :)

**Comment by TheElectronWill** [comment]
Hi
I've got an idea for a more complete fix but haven't implemented it yet because I've been focusing on important school projects. I'll have more time as of tomorrow :)

**Comment by TheElectronWill** [comment]
Successfully tested with `List<List<List<SomeObject>>>`
