### ISSUE TITLE
ConfigSpec.correct() does not correct fields with missing parents

### ISSUE THREAD

**Issue by isturdy** [TheElectronWill/Night-Config#49]
Simple replication (apologies for the Kotlin, that is where I discovered it):
```kotlin
val spec = ConfigSpec()
spec.define("a.b", "")
val config = FileConfig.of("test.toml")
spec.correct(config)
val field: String = config.get("a.b")
```
I expect `field` to be set to `0`; instead, the parent category ("a") is created but empty. A second call to `spec.correct()` does set "a.b", and a loop can correct fields with arbitrary nest depth:
```kotlin
while (!spec.isCorrect(config)) {
   spec.correct(config)
}
```
Because there is a convenient workaround I do not think this is high priority, but from the documentation of `ConfigSpec` this behavior was surprising.

**Comment by TheElectronWill** [comment]
Kotlin is fine, I understand it.

There's indeed a problem here: after a call to `correct()`, `isCorrect()` should return true.
The value `b` should be created with the default value you've defined. Thank you for pointing that out.
