### ISSUE TITLE
TOML ValueWriter does not quote toString results

### ISSUE THREAD

**Issue by tterrag1098** [TheElectronWill/Night-Config#51]
Offending code: https://github.com/TheElectronWill/Night-Config/blob/362d6432fd96bce74106f67b0562813102534e2b/toml/src/main/java/com/electronwill/nightconfig/toml/ValueWriter.java#L49

This should probably be using `StringWriter.writeLiteral`, as currently it outputs invalid TOML, such as for enum values.

See: https://github.com/MinecraftForge/MinecraftForge/issues/5537

**Comment by TheElectronWill** [comment]
Thank you very much for reporting this, it's indeed a mistake to write raw `toString` values. I'll address the issue tomorrow.

**Comment by TheElectronWill** [comment]
Unsupported types shouldn't be written as String though. With the other formats, an exception is thrown when you attempt to write an unsupported type, and it is now (in the new commit) the same for toml.

Enum values aren't supported for now by I can address this.

**Comment by TheElectronWill** [comment]
Enum support incoming
