### ISSUE TITLE
Comments cause Writer to crash when using System.getProperty(line.separator).

### ISSUE THREAD

**Issue by Articdive** [TheElectronWill/Night-Config#55]
When using System.getProperty(line.separator) at the end of comments (to make multiple line comments), you get an ArrayIndexOutOfBoundsException: -1. When I changed it to "\n" then everything worked again, maybe it would be smart to also parse System.getProperty(line.separator) in the Writer.

**Comment by Articdive** [comment]
Obviously this issue is OS Dependent

**Comment by TheElectronWill** [comment]
Thanks for reporting.
Which OS are you using?
Can I have the full stacktrace?

**Comment by Articdive** [comment]
I'm so sorry, I just realized I misspelled "separator" in my code, that was causing the issue.
-_- facepalm.

**Comment by TheElectronWill** [comment]
no problem :)
