### ISSUE TITLE
Trees in Toml are always at the end

### ISSUE THREAD

**Issue by Articdive** [TheElectronWill/Night-Config#59]
For some reason when outputting trees in TOML, they always seem to end up at the end, (even when using a LinkedHashMap!!!
e.g
```
#123
john_1 = "123"
#abc
john_2 = ["john", "Jokes"]
#def
john_3 = "how you doin?"
#hgi
kate_5 = ["kate", "Jokes"]
#hgi
kate_6 = ["kat", "Jokes"]
#hgi
kate_7 = ["ka", "Jokes"]
#hgi
kate_8 = ["k", "Jokes"]

#Johnny
[eva]
	#How are you
	eva = "123"

	[eva.eval]
		#How are you
		eva = "123"
		#How are you
		eve = "123"

#Johnny
[adam]
	#How are you
	eva = "123"

	[adam.eval]
		#How are you
		eva = "123"
		#How are you
		eve = "123"
```
Even though the actual order should be:

john_1
john_2
john_3
eva (tree)
adam (tree)
kate_5
kate_6
kate_7
kate_8

Pretty much the writing of arrays is happening too late and letting nodes after it be written first, causing trees to always be at the end.

**Comment by TheElectronWill** [comment]
This is intended. As per the TOML specification, it's impossible to return to the top level once a table (tree) has been opened.

If you do this:
```toml
a="value"
[table]
  sub="in the table"

after="actually not!!"
```
the entry `after` will be **in the table**
