### ISSUE TITLE
Common names cause unnecessary conflict

### ISSUE THREAD

**Issue by soberyazz** [TheElectronWill/night-config#65]
**Issue:**
Common names cause unnecessary conflict, requiring developers to develop unattractive code.

**Example:**
`com.electronwill.nightconfig.core.conversion.Path` conflicts with `java.nio.file.Path`

**Solution:**
Add a prefix to as many files as you'd like, but primarily those with common names.
`com.electronwill.nightconfig.core.conversion.NCPath` (or any alternative you prefer)

**Comment by soberyazz** [comment]
This can be done with backwards compatibility.

Keep, but add @Depracted where applicable.
com.electronwill.nightconfig.core.conversion.Path

**Comment by TheElectronWill** [comment]
Do you have an example where this is a problem in practice? I don't know many `Path` classes in Java and it seems unlikely at first glance that you would want to store a NIO path in your configuration.

`ValuePath`, `ConfigPath` or `ConfigKey` could be good names for an alternative.
