### ISSUE TITLE
[Question] How do I parse an Array in TOML and retrieve its values to an ArrayList ?

### ISSUE THREAD

**Issue by Dyskal** [TheElectronWill/night-config#73]
Hi, I tried to parse an basic TOML array, but I didn't manage to retrieve the values. Do you have an example of how to do this? Thank you

**Comment by TheElectronWill** [comment]
Hi! If you have a file `config.toml` like this:
```toml
array = [0, 1, 2, 3]
```
just use a `FileConfig` and retrieve the value by its key "array":
```java
FileConfig config = FileConfig.of("path/to/config.toml");
List<Integer> myNumbers = config.get("array");
```
You can read [the wiki](https://github.com/TheElectronWill/night-config/wiki) for more information.

**Comment by TheElectronWill** [comment]
Also note that if you're trying to parse a string that contains only an array an not a full config, like `"[0,1,2,3]"`, then it's not possible in the current version (v3) of NightConfig. An array value isn't by itself a valid toml configuration.

**Comment by Dyskal** [comment]
Hi, this is what I wanted thanks, but now it's says that my list is null do you know why ?
my code : 
```java
import com.electronwill.nightconfig.core.file.FileConfig;

import java.io.*;
import java.util.ArrayList;

public class test {
    public static void main(String[] args) throws IOException {
        File file = new File("config.toml");
        FileConfig config = FileConfig.of(file);
        ArrayList<String> strings = config.get("strings");
        ArrayList<Integer> myNumbers = config.get("numbers");
        System.out.println(myNumbers);
        System.out.println(strings);
    }
}
```
and the config.toml file : 
```toml
strings = ["value1", "value2"]
numbers = [0, 1, 2, 3]
```

**Comment by TheElectronWill** [comment]
Ah yes, I forgot. You must load the config first : `config.load()` 😃

**Comment by Dyskal** [comment]
thank you, i messed up with the `config.load()` in my subclass but now it's working !
