### ISSUE TITLE
Keep new line between commas for TOML arrays

### ISSUE THREAD

**Issue by espidev** [TheElectronWill/night-config#74]
Hey there,
is there a way to keep or add the new line character between commas in a TOML array?

Example:
```toml
array = [
                 "item1",
                 "item2",
                 "item3",
             ]
```
Thanks.

**Comment by TheElectronWill** [comment]
You can create a TomlWriter and use `setIndentArrayElementsPredicate` to tell NightConfig when to write arrays on multiple lines.
See https://javadoc.io/doc/com.electronwill.night-config/toml/latest/com/electronwill/nightconfig/toml/TomlWriter.html
