### ISSUE TITLE
Temporal Parsing doesn't work for years that don't have exactly 4 characters

### ISSUE THREAD

**Issue by Cadiboo** [TheElectronWill/night-config#76]
https://github.com/TheElectronWill/night-config/blob/e534e85d074b65e906ae7dbc4dc7c92e8643e019/toml/src/main/java/com/electronwill/nightconfig/toml/ValueParser.java#L50-L55
Negative years are read as numbers and the temporal parser doesn't handle abnormal dates well.
https://github.com/TheElectronWill/night-config/blob/e534e85d074b65e906ae7dbc4dc7c92e8643e019/toml/src/main/java/com/electronwill/nightconfig/toml/TemporalParser.java#L25-L54

**Comment by TheElectronWill** [comment]
The TOML specification states that date and time follow the RFC 3339, which means that a year is always exactly 4 digits, without a minus sign. Non-compliant dates should be reported as an error (whatever the error is).

Do you have an example of a non-compliant date that is successfully parsed as another type of value?

**Comment by Cadiboo** [comment]
No, I just assumed that I should be able to use objects like `LocalDate.MIN` and have them properly be written and parsed
