### ISSUE TITLE
[Forge Related] Broken order of sections with numbers

### ISSUE THREAD

**Issue by TimeConqueror** [TheElectronWill/night-config#80]
While making mod with Minecraft Forge as a dependency, I noticed that all config values are ordered aplhabetically, but seems this doesn't correctly work with numbers.

I have a config file, that has sections with names: `stage_1`, `stage_2`.
At first time config orders them correctly: stage_1, stage_2, stage_3, stage_4.
But when I load the game subsequent times, it places stage_3 at first, then stage_4, then stage_1 and stage_2, which is rather weird.
Here is an example:
https://gist.github.com/TimeConqueror/b746439ee403d679486f013ecd005578
The first file - first load
The second file - subsequent loads

The config, which Forge uses:
```
 public static class net.minecraftforge.common.ForgeConfigSpec.Builder
    {
        private final Config storage = Config.of(LinkedHashMap::new, InMemoryFormat.withUniversalSupport()); // Use LinkedHashMap for consistent ordering
        ...
   }
```

**Comment by TimeConqueror** [comment]
After long testing, I realized, that this problem is because of HashMap is used in TomlParser#parse method. So it breaks the order of entries.

**Comment by TheElectronWill** [comment]
Hi! Thanks for reporting and sorry for the delay.
There seem to be no explicit use of `HashMap` in the `TomlParser` nor `TableParser`. Does the bug exist outside of forge?

**Comment by TimeConqueror** [comment]
Check in:
TomlParser#parse(CharacterInput input, T destination, ParsingMode parsingMode)

For example on lines 72 and 88:
TableParser.parseNormal(input, this);

Inside it you can see:
```
static CommentedConfig parseNormal(CharacterInput input, TomlParser parser) {
		return parseNormal(input, parser, TomlFormat.instance().createConfig());
	}
```

where `createConfig()` creates a config with HashMap, because this method wasn't overriden in `TomlFormat#INSTANCE`

**Comment by ethanjar** [comment]
I have this same issue when working with Spigot plugins. The sections are completely out of order

**Comment by TheElectronWill** [comment]
> where `createConfig()` creates a config with HashMap, because this method wasn't overriden in `TomlFormat#INSTANCE`

The default implementation of `createConfig` is given [in ConfigFormat.java](https://github.com/TheElectronWill/night-config/blob/stable-3.x/core/src/main/java/com/electronwill/nightconfig/core/ConfigFormat.java#L34).
```java
default C createConfig() {
	return createConfig(Config.getDefaultMapCreator(false));
}
```
The type of map created by `getDefaultMapCreator` depends on the "preserveInsertionOrder" setting, which you should enable to preserve the insertion order for all configurations.

**Solution :**
```java
Config.setInsertionOrderPreserved(true);
```

I'll close this issue, but I will keep in mind two things to improve for NightConfig v4:
- inherit the map creator for sub-configurations, the current behavior is a bit confusing
- preserve insertion order by default, it seems much better for users :smiley:
