### ISSUE TITLE
How to get all bottom-level values with their full path?

### ISSUE THREAD

**Issue by ethanjar** [TheElectronWill/night-config#81]
The valuesMap() simply returns the top level tables with the values as a config. Is there some way to get a map with the keys / path and the value?

[example.toml.txt](https://github.com/TheElectronWill/night-config/files/4518721/example.toml.txt)

For example, I would get a map that contains Global.pvp-override as one of the keys, and the value would be the value in toml (false).

Another entry in the map would be Global.Plot-Snapshots.enabled and the value would reflect what's in the toml file (true)

**Comment by TheElectronWill** [comment]
As of NightConfig v3 you need to code this yourself :-)
You can do this by recursively calling `valuesMap` on each value with type `UnmodifiableConfig`
