### ISSUE TITLE
HOCON writer writes empty strings in an invalid way then can't parse them when reading

### ISSUE THREAD

**Issue by The-Fireplace** [TheElectronWill/night-config#82]
When writing values to a HOCON file, one of the key-value combos I've added to my config is `"serverDefaultClan", ""`, which the HOCON writer then writes like this:
![image](https://user-images.githubusercontent.com/5914284/82840521-87df5700-9e98-11ea-8a59-89b42a376312.png)

Upon trying to read from this config file, the following crash occurs:
https://paste.ubuntu.com/p/zfZ4qQsD6f/

Tested using core-3.6.0 and hocon-3.6.0

**Comment by TheElectronWill** [comment]
That's quite a bug indeed :sweat_smile: Thanks for reporting!
