### ISSUE TITLE
FileConfigBuilder() is private

### ISSUE THREAD

**Issue by Blueil** [TheElectronWill/night-config#88]
FileConfigBuilder() is private and I can't use it because of this.

**Comment by TheElectronWill** [comment]
I'm not sure why you think that :thinking: 
FileConfigBuilder is a public class with a public constructor, see [here](https://github.com/TheElectronWill/night-config/blob/78d9b1cbfc700bacddab903576693f7b89306a80/core/src/main/java/com/electronwill/nightconfig/core/file/FileConfigBuilder.java#L50).
