### ISSUE TITLE
How I can get a section and convert it to a list?

### ISSUE THREAD

**Issue by Blueil** [TheElectronWill/night-config#89]
How I can get a section and convert it to a list?
Instead of:
`list = [data, "string", 1]`
I want to use this:
[list]
  data
  "string"
  1

**Comment by TheElectronWill** [comment]
In TOML a section (actual name "table" in TOML) is a dictionary/hashtable, not a list. You cannot use a table as a list, it's not the same data structure.
Valid section:
```toml
[section]
key = "value"
thing = 2.0
```

Invalid section:
```toml
[section]
"value"
2.0
```

**Comment by Blueil** [comment]
> In TOML a section (actual name "table" in TOML) is a dictionary/hashtable, not a list. You cannot use a table as a list, it's not the same data structure.
> Valid section:
> 
> ```toml
> [section]
> key = "value"
> thing = 2.0
> ```
> 
> Invalid section:
> 
> ```toml
> [section]
> "value"
> 2.0
> ```
> 
> You can [learn more about the TOML format here](https://toml.io/en/) :-)

I don't like the `list = [data, "string", 1]`
So how I can use this:
```
[list]
    [list.name]
        key = "value"
```
