### ISSUE TITLE
How to make a section an array of tables?

### ISSUE THREAD

**Issue by JordanPlayz158** [TheElectronWill/night-config#90]
Hello, I have been trying for hours to see how you would have the config detect a subconfig as an array of tables (so I can have a list of objects) but everything I have tried just results in a normal section. I'm sure the functionality is implemented it's just I am unable to find any examples or documentation on how to do it.

**Comment by TheElectronWill** [comment]
Hello!

If you have a config with an array of tables like this:
```toml
[[array]]
key = "value"

[[array]]
key2 = "value2"
```

You should be able to get a list of configurations like this:
```java
List<Config> list = config.get("array");
Config firstSubConfig = list.get(0);
// Config is com.electronwill.nightconfig.core.Config
```

**Comment by JordanPlayz158** [comment]
Thank you!
