### ISSUE TITLE
Lists in config can't be cast into lists

### ISSUE THREAD

**Issue by Blueil** [TheElectronWill/night-config#91]
I have a list in the config
`list = ["example1", "example2"]`
And I want to use it in a for-each loop.
I tried to cast it as `List`, `ArrayList` and `String[]` and it giving an error that tells that `Arrays$ArrayList` can't be cast into `ArrayList`

**Comment by TheElectronWill** [comment]
Use the `List` interface (not ArrayList!) and it should work:
```java
List<String> myList = config.get("list");
```
with `import java.util.List`
