### ISSUE TITLE
[HOCON] Incorrectly parses number types

### ISSUE THREAD

**Issue by isXander** [TheElectronWill/night-config#94]
Given a hocon file like this
```hocon
my_float=1.0
```
And then you load the config with this value (from a file)
```java
var cfg = FileConfig.of(HoconFormat.instance());
var my_float = cfg.get<Float>("my_float");
```
with the result of
```
ClassCastException: Cannot cast Integer to Float
```

**Comment by TheElectronWill** [comment]
HOCON parsing is done by https://github.com/lightbend/config. NightConfig provides a wrapper around it to unify the API but that's all. You could try
```java
var myFloat = cfg.get<Number>("my_float").floatValue()
```

**Comment by TheElectronWill** [comment]
There is an issue in typesafeconfig for your problem: https://github.com/lightbend/config/issues/610
