### ISSUE TITLE
Hexadecimal numbers containing e/E are not accepted

### ISSUE THREAD

**Issue by Vazkii** [TheElectronWill/night-config#96]
`Caused by: com.electronwill.nightconfig.core.io.ParsingException: Invalid value: 0xe5e64d`

This is caused by validating the exponential symbol before checking the base.
https://github.com/TheElectronWill/night-config/blob/78d9b1cbfc700bacddab903576693f7b89306a80/toml/src/main/java/com/electronwill/nightconfig/toml/ValueParser.java#L96-L103

**Comment by sciwhiz12** [comment]
This seems to have been fixed by #95, which is waiting in the `stable-3.x` branch for a new release.

**Comment by TheElectronWill** [comment]
I've moved night-config 3 back to the master branch, it's cleaner this way (and the master become green, hurray!).
The bug is fixed and I will make a new release very soon.
