### ISSUE TITLE
Reading specified generic type from .toml config

### ISSUE THREAD

**Issue by SSKirillSS** [TheElectronWill/night-config#97]
Hello. I have a some sort of auto-fillable .toml configs, and this config contains a specified generic type. It perfectly reads data from config, but I ran into the problem when I tried to convert this data to my object. It just returns a non-specific empty type of my object.

Previously, before switching to night-config I've used GSON lib, that contains a way to read this sort of generic data:
```
  /**
   * This method deserializes the Json read from the specified reader into an object of the
   * specified type. This method is useful if the specified object is a generic type. For
   * non-generic objects, use {@link #fromJson(Reader, Class)} instead. If you have the Json in a
   * String form instead of a {@link Reader}, use {@link #fromJson(String, Type)} instead.
   *
   * @param <T> the type of the desired object
   * @param json the reader producing Json from which the object is to be deserialized
   * @param typeOfT The specific genericized type of src. You can obtain this type by using the
   * {@link com.google.gson.reflect.TypeToken} class. For example, to get the type for
   * {@code Collection<Foo>}, you should use:
   * <pre>
   * Type typeOfT = new TypeToken&lt;Collection&lt;Foo&gt;&gt;(){}.getType();
   * </pre>
   * @return an object of type T from the json. Returns {@code null} if {@code json} is at EOF.
   * @throws JsonIOException if there was a problem reading from the Reader
   * @throws JsonSyntaxException if json is not a valid representation for an object of type
   * @since 1.2
   */
  @SuppressWarnings("unchecked")
  public <T> T fromJson(Reader json, Type typeOfT) throws JsonIOException, JsonSyntaxException {
    JsonReader jsonReader = newJsonReader(json);
    T object = (T) fromJson(jsonReader, typeOfT);
    assertFullConsumption(object, jsonReader);
    return object;
  }
```

So now I'm wondering, is there a way to do something like it with .toml or even any other types of night-config.

Sourcecode: https://github.com/SSKirillSS/relics

Example data class: https://github.com/SSKirillSS/relics/blob/master/src/main/java/it/hurts/sskirillss/relics/items/relics/hands/RageGloveItem.java#L124
Data parent class: https://github.com/SSKirillSS/relics/blob/master/src/main/java/it/hurts/sskirillss/relics/items/relics/base/data/RelicStats.java
Config handler class: https://github.com/SSKirillSS/relics/blob/master/src/main/java/it/hurts/sskirillss/relics/configs/RelicConfig.java
Generated config: https://pastebin.com/FfMHiJBM

**Comment by TheElectronWill** [comment]
Hello,

If I understand correctly you want to serialize a List<T>? There is nothing similar to TypeToken in NightConfig but it's still possible. As explained in issue #69, generic lists are supported out of the box.

If that's not enough, you can always use a `@Conversion` annotation ([example](https://github.com/TheElectronWill/night-config/blob/master/examples/src/main/java/ObjectConverterAnnotationsExample.java)).
